export const DO_LOGIN = " DO_LOGIN";
export const SET_BALANCE_STUDENT = "SET_BALANCE_STUDENT";
export const SET_BALANCE_VICTIM1 = "SET_BALANCE_VICTIN1";
export const SET_BALANCE_VICTIM2 = "SET_BALANCE_VICTIM2";
export const ADD_MESSAGE = "ADD_MESSAGE";
